from __future__ import annotations

from contextlib import AbstractContextManager
from datetime import date
from typing import Protocol, Sequence

from .domain import Candle, Instrument


class MarketDataUnavailableError(RuntimeError):
    """The provider has no candles for the requested date range."""


class MarketDataProvider(Protocol):
    name: str

    def daily_history(self, instrument: Instrument, start: date, end: date) -> list[Candle]: ...


class MarketRepository(Protocol):
    def transaction(self) -> AbstractContextManager["MarketRepository"]: ...
    def migrate(self) -> None: ...
    def upsert_instruments(self, instruments: Sequence[Instrument]) -> None: ...
    def upsert_candles(self, candles: Sequence[Candle]) -> int: ...
    def first_candle_date(self, symbol: str, timeframe: str) -> date | None: ...
    def last_candle_date(self, symbol: str, timeframe: str) -> date | None: ...
    def last_sync_through(self, symbol: str, timeframe: str) -> date | None: ...
    def is_backfill_complete(self, symbol: str, timeframe: str) -> bool: ...
    def mark_backfill_complete(self, symbol: str, timeframe: str, checked_from: date) -> None: ...
    def data_version(self) -> tuple[int, int]: ...
    def latest_candles(self, timeframe: str) -> list[Candle]: ...
    def candle_series(self, timeframe: str, limit_per_symbol: int | None = None) -> dict[str, list[Candle]]: ...
    def record_sync(self, symbol: str, timeframe: str, status: str, rows: int, message: str = "", attempted_through: date | None = None) -> None: ...
